version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Host"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/Host.Tests"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
