version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Host"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/Host.Tests"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
